#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
apiVersion: v2
appVersion: 0.9.1
description: Apache Gravitino is a high-performance, geo-distributed, and federated metadata lake. It manages the metadata directly in different sources, types, and regions. It also provides users with unified metadata access for data and AI assets.
home: https://gravitino.apache.org
annotations:
  licenses: Apache-2.0
dependencies:
  - condition: mysql.enabled
    name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 10.2.1
kubeVersion: '>=1.29.0-0'
maintainers:
  - name: Gravitino
    email: dev@gravitino.apache.org
    url: https://gravitino.apache.org
name: gravitino
sources:
  - https://github.com/apache/gravitino
version: 0.9.9
