version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Java (Gradle) : Single root entry is enough because settings.gradle.kts includes all submodules
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"

  # NPM
  - package-ecosystem: "npm"
    directory: "/web/web"
    schedule:
      interval: "monthly"

  # PYTHON
  - package-ecosystem: "pip"
    directory: "/mcp-server"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/clients/client-python"
    schedule:
      interval: "monthly"
